### get tools
GET {{host}}/infra-tools?page=2&limit=4

### create tool
POST {{host}}/infra-tools
Content-Type: application/json

{
  "name": "DeSchool",
  "type":"dao.tool",
  "description": "DeSchool is a tool for schools"
}


### update tool
PUT {{host}}/infra-tools/ePo2T6hL
Content-Type: application/json

{
  "url":"https://deschool.app"
}

### delete tool
DELETE {{host}}/tools/MDYxZDdlNjQ3MDAxLTQwYjktYjE5ZC1jZmJkZTNmYjNkZTI=