/**
 * SeeDao-OS-API
 * SeeDao-OS-API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface DotbitControllerConsumeKeyRequest
 */
export interface DotbitControllerConsumeKeyRequest {
    /**
     *
     * @type {string}
     * @memberof DotbitControllerConsumeKeyRequest
     */
    'key': string;
    /**
     *
     * @type {string}
     * @memberof DotbitControllerConsumeKeyRequest
     */
    'address': string;
    /**
     *
     * @type {string}
     * @memberof DotbitControllerConsumeKeyRequest
     */
    'subDID': string;
}
