/**
 * SeeDao-OS-API
 * SeeDao-OS-API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PagedResult } from './paged-result';
import { PaginatedResponseOfToolDtoAllOf } from './paginated-response-of-tool-dto-all-of';
/**
 * @type PaginatedResponseOfToolDto
 * @export
 */
export type PaginatedResponseOfToolDto = PagedResult & PaginatedResponseOfToolDtoAllOf;
