/**
 * SeeDao-OS-API
 * SeeDao-OS-API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface SGNMintRecordModel
 */
export interface SGNMintRecordModel {
    /**
     *
     * @type {number}
     * @memberof SGNMintRecordModel
     */
    'id': number;
    /**
     *
     * @type {string}
     * @memberof SGNMintRecordModel
     */
    'address': string;
    /**
     *
     * @type {number}
     * @memberof SGNMintRecordModel
     */
    'tokenId': number;
    /**
     *
     * @type {string}
     * @memberof SGNMintRecordModel
     */
    'subDID': string;
    /**
     *
     * @type {string}
     * @memberof SGNMintRecordModel
     */
    'timestamp': string;
    /**
     *
     * @type {string}
     * @memberof SGNMintRecordModel
     */
    'contract': string;
}
