/**
 * SeeDao-OS-API
 * SeeDao-OS-API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface SubDIDCdKeyDto
 */
export interface SubDIDCdKeyDto {
    /**
     *
     * @type {string}
     * @memberof SubDIDCdKeyDto
     */
    'key': string;
    /**
     *
     * @type {boolean}
     * @memberof SubDIDCdKeyDto
     */
    'isValid': boolean;
    /**
     *
     * @type {string}
     * @memberof SubDIDCdKeyDto
     */
    'address'?: string;
    /**
     *
     * @type {string}
     * @memberof SubDIDCdKeyDto
     */
    'subDID'?: string;
}
