/**
 * SeeDao-OS-API
 * SeeDao-OS-API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ToolUpdateInput
 */
export interface ToolUpdateInput {
    /**
     * name
     * @type {string}
     * @memberof ToolUpdateInput
     */
    'name'?: string;
    /**
     *
     * @type {string}
     * @memberof ToolUpdateInput
     */
    'type'?: string;
    /**
     *
     * @type {string}
     * @memberof ToolUpdateInput
     */
    'logo'?: string;
    /**
     *
     * @type {string}
     * @memberof ToolUpdateInput
     */
    'description'?: string;
    /**
     *
     * @type {string}
     * @memberof ToolUpdateInput
     */
    'url'?: string;
}
