/**
 * SeeDao-OS-API
 * SeeDao-OS-API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ToolCreateInput
 */
export interface ToolCreateInput {
    /**
     *
     * @type {string}
     * @memberof ToolCreateInput
     */
    'name': string;
    /**
     *
     * @type {string}
     * @memberof ToolCreateInput
     */
    'type': string;
    /**
     *
     * @type {string}
     * @memberof ToolCreateInput
     */
    'logo'?: string;
    /**
     *
     * @type {string}
     * @memberof ToolCreateInput
     */
    'description'?: string;
    /**
     *
     * @type {string}
     * @memberof ToolCreateInput
     */
    'url'?: string;
}
