/* tslint:disable */
/* eslint-disable */
/**
 * SeeDao-OS-API
 * SeeDao-OS-API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DotbitControllerMintRequest
 */
export interface DotbitControllerMintRequest {
    /**
     * 
     * @type {string}
     * @memberof DotbitControllerMintRequest
     */
    'address': string;
    /**
     * 
     * @type {string}
     * @memberof DotbitControllerMintRequest
     */
    'subDID': string;
    /**
     * 
     * @type {string}
     * @memberof DotbitControllerMintRequest
     */
    'signature': string;
}

