/* tslint:disable */
/* eslint-disable */
/**
 * SeeDao-OS-API
 * SeeDao-OS-API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InsertSGNMintRecordDto
 */
export interface InsertSGNMintRecordDto {
    /**
     * 
     * @type {string}
     * @memberof InsertSGNMintRecordDto
     */
    'address': string;
    /**
     * 
     * @type {number}
     * @memberof InsertSGNMintRecordDto
     */
    'tokenId': number;
    /**
     * 
     * @type {string}
     * @memberof InsertSGNMintRecordDto
     */
    'subDID': string;
    /**
     * 
     * @type {string}
     * @memberof InsertSGNMintRecordDto
     */
    'contract': string;
}

