/* tslint:disable */
/* eslint-disable */
/**
 * SeeDao-OS-API
 * SeeDao-OS-API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PagedResult } from './paged-result';
// May contain unused imports in some cases
// @ts-ignore
import { PaginatedResponseOfToolDtoAllOf } from './paginated-response-of-tool-dto-all-of';
// May contain unused imports in some cases
// @ts-ignore
import { ToolDto } from './tool-dto';

/**
 * @type PaginatedResponseOfToolDto
 * @export
 */
export type PaginatedResponseOfToolDto = PagedResult & PaginatedResponseOfToolDtoAllOf;


