/* tslint:disable */
/* eslint-disable */
/**
 * SeeDao-OS-API
 * SeeDao-OS-API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ToolDto } from './tool-dto';

/**
 * 
 * @export
 * @interface PaginatedResponseOfToolDtoAllOf
 */
export interface PaginatedResponseOfToolDtoAllOf {
    /**
     * 
     * @type {Array<ToolDto>}
     * @memberof PaginatedResponseOfToolDtoAllOf
     */
    'items'?: Array<ToolDto>;
}

