/* tslint:disable */
/* eslint-disable */
/**
 * SeeDao-OS-API
 * SeeDao-OS-API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ToolDto
 */
export interface ToolDto {
    /**
     * 
     * @type {string}
     * @memberof ToolDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ToolDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ToolDto
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof ToolDto
     */
    'logo': string;
    /**
     * 
     * @type {string}
     * @memberof ToolDto
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof ToolDto
     */
    'url': string;
    /**
     * 
     * @type {string}
     * @memberof ToolDto
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof ToolDto
     */
    'createdBy': string;
}

