/**
 * SeeDao-OS-API
 * SeeDao-OS-API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { RequestArgs, BaseAPI } from '../base';
import { PaginatedResponseOfToolDto } from '../types';
import { ToolCreateInput } from '../types';
import { ToolDto } from '../types';
import { ToolUpdateInput } from '../types';
/**
 * InfraToolsApi - axios parameter creator
 * @export
 */
export declare const InfraToolsApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {ToolCreateInput} toolCreateInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    toolControllerCreate: (toolCreateInput: ToolCreateInput, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    toolControllerDelete: (id: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @param {number} [page]
     * @param {number} [limit]
     * @param {boolean} [includeTotal]
     * @param {string} [order] id,-name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    toolControllerGetList: (page?: number, limit?: number, includeTotal?: boolean, order?: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @param {string} id
     * @param {ToolUpdateInput} toolUpdateInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    toolControllerUpdate: (id: string, toolUpdateInput: ToolUpdateInput, options?: AxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * InfraToolsApi - functional programming interface
 * @export
 */
export declare const InfraToolsApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {ToolCreateInput} toolCreateInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    toolControllerCreate(toolCreateInput: ToolCreateInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ToolDto>>;
    /**
     *
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    toolControllerDelete(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ToolDto>>;
    /**
     *
     * @param {number} [page]
     * @param {number} [limit]
     * @param {boolean} [includeTotal]
     * @param {string} [order] id,-name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    toolControllerGetList(page?: number, limit?: number, includeTotal?: boolean, order?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedResponseOfToolDto>>;
    /**
     *
     * @param {string} id
     * @param {ToolUpdateInput} toolUpdateInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    toolControllerUpdate(id: string, toolUpdateInput: ToolUpdateInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ToolDto>>;
};
/**
 * InfraToolsApi - factory interface
 * @export
 */
export declare const InfraToolsApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {ToolCreateInput} toolCreateInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    toolControllerCreate(toolCreateInput: ToolCreateInput, options?: any): AxiosPromise<ToolDto>;
    /**
     *
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    toolControllerDelete(id: string, options?: any): AxiosPromise<ToolDto>;
    /**
     *
     * @param {number} [page]
     * @param {number} [limit]
     * @param {boolean} [includeTotal]
     * @param {string} [order] id,-name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    toolControllerGetList(page?: number, limit?: number, includeTotal?: boolean, order?: string, options?: any): AxiosPromise<PaginatedResponseOfToolDto>;
    /**
     *
     * @param {string} id
     * @param {ToolUpdateInput} toolUpdateInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    toolControllerUpdate(id: string, toolUpdateInput: ToolUpdateInput, options?: any): AxiosPromise<ToolDto>;
};
/**
 * InfraToolsApi - object-oriented interface
 * @export
 * @class InfraToolsApi
 * @extends {BaseAPI}
 */
export declare class InfraToolsApi extends BaseAPI {
    /**
     *
     * @param {ToolCreateInput} toolCreateInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InfraToolsApi
     */
    toolControllerCreate(toolCreateInput: ToolCreateInput, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<ToolDto, any>>;
    /**
     *
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InfraToolsApi
     */
    toolControllerDelete(id: string, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<ToolDto, any>>;
    /**
     *
     * @param {number} [page]
     * @param {number} [limit]
     * @param {boolean} [includeTotal]
     * @param {string} [order] id,-name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InfraToolsApi
     */
    toolControllerGetList(page?: number, limit?: number, includeTotal?: boolean, order?: string, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<PaginatedResponseOfToolDto, any>>;
    /**
     *
     * @param {string} id
     * @param {ToolUpdateInput} toolUpdateInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InfraToolsApi
     */
    toolControllerUpdate(id: string, toolUpdateInput: ToolUpdateInput, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<ToolDto, any>>;
}
