name: Fly Deploy
on:
  push:
    branches:
      - nestjs-prisma-bak
# env:
#   DATABASE_URL: ${{ secrets.DATABASE_URL }}
#   DOTBIT_SeeDAO_PRIVATE_KEY: ${{ secrets.DOTBIT_SeeDAO_PRIVATE_KEY }}
#   JWT_SECRET: ${{ secrets.JWT_SECRET }}
#   JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}

# jobs:
#   deploy:
#     name: Deploy app
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: superfly/flyctl-actions/setup-flyctl@master
#       - run: flyctl deploy --remote-only
#         env:
#           FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
